# Generated by Django 5.1.3 on 2024-11-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres_tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RandomTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('like', models.IntegerField(default=0, verbose_name='Лайк (импровизированный)')),
                ('genres', models.ManyToManyField(to='main.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Рандомные произведения',
                'verbose_name_plural': 'Рандомные произведения',
            },
        ),
    ]
