# Generated by Django 5.1.3 on 2024-11-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomtitle',
            name='images',
            field=models.ImageField(upload_to='product', verbose_name='Изображение'),
        ),
    ]
