# Generated by Django 5.1.3 on 2024-11-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_randomtitle_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RandomTitle',
            new_name='RanobeTitle',
        ),
    ]
